github.com:
    users:
        Madi-Engine-Core75:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Madi-Engine-Core75
